name: Build x86_64

on: release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build arai2c.exe
      run: |
        curl -L -o Dockerfile.mingw "https://raw.githubusercontent.com/aria2/aria2/master/Dockerfile.mingw"
        patch Dockerfile.mingw < Dockerfile.mingw_x64.patch
        sudo docker build -t aria2-mingw - < Dockerfile.mingw
        id=$(sudo docker create aria2-mingw)
        sudo docker cp $id:/aria2/src/aria2c.exe ./aria2c-fast_x64.exe
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: aria2c-fast_x64.exe application/vnd.microsoft.portable-executable
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
