name: Build x86

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build arai2c.exe
      run: |
        curl -L -o Dockerfile.mingw "https://raw.githubusercontent.com/aria2/aria2/master/Dockerfile.mingw"
        patch -Np1 < Dockerfile.mingw_x86.patch
        sudo docker build -t aria2-mingw - < Dockerfile.mingw_x86
        id=$(sudo docker create aria2-mingw)
        sudo docker cp $id:/aria2/src/aria2c.exe ./aria2c-fast_x86.exe
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: aria2c-fast_x86.exe application/vnd.microsoft.portable-executable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
